name: run-go-tests

env:
  GO111MODULE: on

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
  schedule:
    - cron: '* 22 * * *'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.14.x, 1.15.x ]
        os: [ ubuntu-latest ]
        #os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run lint and tests
        run: make test-travis
      - name: Update code coverage
        run: bash <(curl -s https://codecov.io/bash)